# Generated by Django 5.0.7 on 2024-09-14 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(default=True)),
                ('is_deliberated', models.BooleanField(default=False)),
                ('probable_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_employe', models.CharField(max_length=50, unique=True)),
                ('specialite', models.CharField(max_length=100)),
                ('option_section', models.CharField(default='default_section', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('Promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='IscApp.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=5, max_length=100)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue', to='IscApp.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prénom', models.CharField(max_length=50)),
                ('adressephysique', models.CharField(blank=True, max_length=560, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('motdepasse', models.CharField(default='default_motdepasse', max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user_type', models.CharField(choices=[('administrateur', 'Administrateur'), ('enseignant', 'Enseignant'), ('etudiant', 'Etudiant')], default='etudiant', max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomUsers',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('option_section', models.CharField(default='default_section', max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('Promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='IscApp.promotion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('Premier Semestre', 'Premier Semestre'), ('Deuxième Semestre', 'Deuxième Semestre')], default='semestre', max_length=20)),
                ('matiere', models.CharField(blank=True, max_length=100)),
                ('categorie', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('credit', models.IntegerField(default=0)),
                ('cote', models.FloatField(default=0.0)),
                ('credits_capitalises', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('travail_pratique', models.FloatField(default=0.0)),
                ('interrogation', models.FloatField(default=0.0)),
                ('examen', models.FloatField(default=0.0)),
                ('total', models.FloatField(blank=True, default=0.0)),
                ('moyenne', models.FloatField(blank=True, default=0.0)),
                ('pourcentage', models.FloatField(blank=True, default=0.0)),
                ('validation', models.CharField(blank=True, choices=[('Validé', 'Validé'), ('Non validé', 'Non validé')], max_length=20)),
                ('mention', models.CharField(blank=True, max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='IscApp.etudiant')),
                ('ue', models.ForeignKey(default='ue', on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='IscApp.ue')),
            ],
            options={
                'unique_together': {('etudiant', 'ue')},
            },
        ),
    ]
