# Generated by Django 5.0.6 on 2024-07-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IscApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adressephysique',
            field=models.CharField(blank=True, max_length=560, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
